<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Version>1.0.0</Version>
    <Company>VintagePlayers</Company>
    <Product>VintageDrive</Product>
    <Copyright>© 2026 VintagePlayers — Licence MIT</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
